version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"  # Expose port 8000 for the Django app
    volumes:
      - .:/app
    environment:
      - DEBUG=True  # Ensure DEBUG is set to True for development

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A amazon_scraper worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A amazon_scraper beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
