# Generated by Django 5.1.2 on 2024-10-21 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Amazon brand', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=255)),
                ('asin', models.CharField(help_text='Amazon Standard Identification Number (ASIN)', max_length=10, unique=True)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit (SKU)', max_length=50, null=True)),
                ('image', models.URLField(help_text='URL of the product image', max_length=500)),
                ('brand', models.ForeignKey(help_text='Brand to which the product belongs', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='scraper.brand')),
            ],
        ),
    ]
