# Generated by Django 5.1.2 on 2024-10-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='last_scraped',
            field=models.DateTimeField(blank=True, help_text='The last time products were scraped for this brand', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='scrape_frequency',
            field=models.IntegerField(default=6, help_text='Frequency of scraping in hours'),
        ),
    ]
